name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      # - name: Setup Java 8
      #   id: setup-java-8
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '8'
      #     check-latest: false

      - name: Setup Java 11
        id: setup-java-11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false

      - name: Test JAVA_HOME
        run: |
          env | grep -i 'java'

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.2

      - name: Setup platform tools
        run: sdkmanager platform-tools

      - name: Test Android env
        run: |
          echo "ANDROID_HOME = $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT = $ANDROID_SDK_ROOT"

      - name: Assemble artifact
        run: |
          ./gradlew assemble